apiVersion: apps/v1
kind: Deployment
metadata:
  name: automotivesalesservice-deployment
  labels:
    app: automotivesalesservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automotivesalesservice-app
  template:
    metadata:
      labels:
        app: automotivesalesservice-app
    spec:
      containers:
        - name: automotivesalesservice-app
          image: arthurgabriel73/automotivesalesservice:1.0
          ports:
            - containerPort: 8081
          env:
            - name: DATASOURCE_URL
              value: postgres-db-automotivesalesservice-service
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_SALES_SERVICE_DATABASE
            - name: AUTOMOTIVESALES_HUB_URL
              value: "http://automotivesaleshub-app-service:8080"
          resources:
            requests:
              cpu: "550m"
            limits:
              cpu: "800m"
---
apiVersion: v1
kind: Service
metadata:
  name: automotivesalesservice-app-service
spec:
  type: LoadBalancer
  selector:
    app: automotivesalesservice-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
