apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db-hub
  template:
    metadata:
      labels:
        app: postgres-db-hub
    spec:
      containers:
        - name: postgres-db
          image: postgres:16.3
          env:
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_ROOT_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_SALES_HUB_DATABASE
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-automotivesaleshub-service
spec:
  type: LoadBalancer
  selector:
    app: postgres-db-hub
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
